IoTPlatform/IoTPlatform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('MonitoringApp.urls')),
    path("", include('users.urls')),
    # path("Monitoring/", include(django.contrib.auth.urls))
    
]

IoTPlatform/MonitoringApp/urls.py
from django.urls import path,include
from . import views

app_name = 'MonitoringApp'

urlpatterns = [
   
    # path('', views.register, name='register'),
    # path('login/', views.login_view, name='login'),
    # path('register/', views.register_view, name='register_view'),
    path('', views.show_dashbord, name='dashbord'),
    path('graph/', views.show_graph, name='show_graph'),
    path('fetch_sensor_values_ajax/', views.fetch_sensor_values_ajax, name='fetch_sensor_values_ajax'),
    path('post_sensor_values_ajax/', views.post_sensor_values_ajax, name='post_sensor_values_ajax'),

    
   
   
    
]

IoTPlatform/users/urls.py
from django.urls import path, include
from . import views


urlpatterns = [

    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='user-logout'),
    path('register/', views.user_register, name='user-register'),

]

IoTPlatform/MonitoringApp/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class SensorData(models.Model):
    sensor_name = models.CharField(max_length=255)
    ecg_data = models.TextField()  # Stocare de date brute de la ECG
    spo2_level = models.FloatField()  # Cantitatea de oxigen din sânge
    heart_rate = models.IntegerField()  # Ritmul cardiac
    fall_detected = models.BooleanField(default=False)  # Alarmă de cădere
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sensor_name} at {self.timestamp}'

IoTPlatform/MonitoringApp/views.py
from datetime import datetime, timedelta
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import random
from .models import Post, SensorData  # Importăm modelul SensorData


import sqlite3

con = sqlite3.connect("sensor_data.db")
con.execute("CREATE TABLE IF NOT EXISTS sensor_data(timestamp, sensor_name, ecg_data, spo2_level, heart_rate, temp, fall_detected)")

#
# def register(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()  # Salvează utilizatorul în baza de date
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password1')  # Folosim 'password1' pentru a obține parola
#             user = authenticate(username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('MonitoringApp/dashboard.html')
#     else:
#         form = UserCreationForm()
#     return render(request, 'MonitoringApp/register.html', {'form': form})
#
#
# def login_view(request):
#     if request.user.is_authenticated:
#         return redirect('MonitoringApp/dashboard.html')
#
#     if request.method == 'POST':
#         form = AuthenticationForm(request, request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             return redirect('MonitoringApp/dashboard.html')
#     else:
#         form = AuthenticationForm()
#     return render(request, 'MonitoringApp/login.html', {'form': form})
#
#
# def register_view(request):
#     posts = Post.objects.all()  # Obține toate articolele din baza de date
#     return render(request, 'MonitoringApp/register.html', {'posts': posts})


@login_required(login_url='user-login')
def show_graph(request, template_name='MonitoringApp/live_graph.html'):
    return render(request, template_name)


@login_required(login_url='user-login')
def fetch_sensor_values_ajax(request):
    data = {}
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        try:
            con = sqlite3.connect("sensor_data.db")
            cursor = con.cursor()
            result = cursor.execute("SELECT timestamp, ecg_data, spo2_level, heart_rate, temp, fall_detected FROM sensor_data ORDER BY timestamp DESC LIMIT 1;")
            row = result.fetchone()
            if row:
                timestamp, ecg_data, spo2_level, heart_rate, temp, fall_detected = row
                sensor_data_array = {
                    'timestamp': timestamp,
                    'ecg_data': ecg_data if ecg_data is not None else 0.0,
                    'spo2_level': spo2_level if spo2_level is not None else 0,
                    'heart_rate': heart_rate if heart_rate is not None else 0,
                    'temp': temp if temp is not None else 0,
                    'fall_detected': fall_detected if fall_detected is not None else False,
                }
                
                data['fall_detected'] = fall_detected
                data['heart_rate'] = heart_rate
                data['spo2_level'] = spo2_level

                
                
            else:
                sensor_data_array = [{
                    'timestamp': datetime.now(),
                    'ecg_data': 0.0,
                    'spo2_level': 0,
                    'heart_rate': 0,
                    'fall_detected': False,
                }]
                data['fall_detected'] = False
                pass

            cursor.close()
            con.close()

            data['result'] = sensor_data_array
            print("Sensor data:", sensor_data_array)

        except Exception as e:
            print(f"Error reading sensor data: {e}")
            # sensor_data_array = {
            #     'timestamp': datetime.now(),
            #     'ecg_data': 0.0,
            #     'spo2_level': 0,
            #     'heart_rate': 0,
            #     'temp': 0,
            #     'fall_detected': False,
            # }
            # data['fall_detected'] = False
            # data['result'] = sensor_data_array

    else:
        data['result'] = 'Not Ajax'

    return JsonResponse(data)


@csrf_exempt
def post_sensor_values_ajax(request):
    try:
        sensor_data = json.loads(request.body)
        sensor_data["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        fall_detected = True if sensor_data.get('fall_detected') == 'true' else False
        
        # Salvarea datelor în baza de date SQLite
        con = sqlite3.connect("sensor_data.db")
        cursor = con.cursor()

        cursor.execute("""
            INSERT INTO sensor_data (timestamp, sensor_name, ecg_data, spo2_level, heart_rate, temp, fall_detected) 
            VALUES (:timestamp, :sensor_name, :ecg_data, :spo2_level, :heart_rate, :temp, :fall_detected)
        """, sensor_data)
        con.commit()
        cursor.close()
        con.close()

        return JsonResponse({"ok": True})
    
    except Exception as e:
        print(f"Error saving sensor data: {e}")
        return JsonResponse({"ok": False})


@login_required(login_url='user-login')
def show_dashbord(request, template_name='MonitoringApp/dashboard.html'):
    return render(request, template_name)

IoTPlatform/MonitoringApp/templates/MonitoringApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>IOT PLATFORM</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'mainPage/style.css'%}"
    />

    <link
      rel="stylesheet"
      href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css'%}"
    />
  </head>
  <body>
    {% block body%} {% endblock %}

    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
  </body>
</html>

IoTPlatform/MonitoringApp/templates/MonitoringApp/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h1>Istoric alerte</h1>
<a class="btn btn-primary" href="{% url 'MonitoringApp:show_graph' %}"
  >Real-time data from Sensor</a>

{% endblock %}

IoTPlatform/MonitoringApp/templates/MonitoringApp/live_graph.html
{% extends 'base.html' %}

    {% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome.css' %}" />
    <style>
      body {
        font-family: "Roboto", Arial, sans-serif;
        background-color: #f8f9fa;
        color: #495057;
        margin: 0;
        padding: 0;
      }
      .container-fluid {
        padding: 0;
      }
      .sidebar {
        height: 100%;
        width: 250px;
        position: fixed;
        top: 0;
        left: 0;
        background-color: #343a40;
        padding-top: 20px;
      }
      .sidebar a {
        padding: 10px 15px;
        text-decoration: none;
        font-size: 18px;
        color: #f8f9fa;
        display: block;
        transition: 0.3s;
      }
      .sidebar a:hover {
        background-color: #495057;
      }
      .sidebar .active {
        background-color: #007bff;
      }
      .main-content {
        margin-left: 250px;
        padding: 20px;
      }
      h1 {
        color: #007bff;
        margin-bottom: 20px;
      }
      .sensor-data {
        margin-top: 20px;
        padding: 20px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }
      .sensor-value {
        font-size: 3em;
        font-weight: bold;
        color: #007bff;
        display: inline;
      }
      .sensor-unit {
        font-size: 1.5em;
        color: #007bff;
        display: inline;
      }
      .sensor-label {
        font-size: 1.2em;
        font-weight: bold;
        margin-top: 10px;
        color: #007bff;
      }
      .alert-message {
        font-size: 1.2em;
        font-weight: bold;
        margin-top: 5px;
        /*text-align: center; */
      }
      .fall-detected {
        color: #dc3545;
      }
      .nofall {
        color: #28a745;
      }
      .chart-container {
        margin-top: 30px;
      }
      .card {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }
      .card-header {
        background-color: #007bff;
        color: white;
        padding: 10px;
        border-radius: 6px 6px 0 0;
      }
      .card-body {
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
      <div class="sidebar">
        <a href="#" class="active">Dashboard</a>

        <a href="#">Istoric Alerte</a>
      </div>

      <div class="main-content">
        <h1>IoT Platform Dashboard</h1>

        <div class="row chart-container">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">ECG</div>
              <div class="card-body">
                <div id="chartContainer1" style="height: 400px"></div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">Heart Rate</div>
              <div class="card-body">
                <div id="chartContainer2" style="height: 400px"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="row chart-container">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">SPO2 Levels</div>
              <div class="card-body">
                <div id="chartContainer3" style="height: 400px"></div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">Temperature</div>
              <div class="card-body">
                <div id="chartContainer4" style="height: 400px"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">Sensor Data</div>
                <div class="card-body sensor-data">
                  <!--<div class="sensor-label">ECG</div>
                  <div class="sensor-value" id="ecg_value">--</div>
                  <div class="sensor-unit">mm</div>-->
                  <div class="sensor-label">Heart Rate</div>
                  <div class="sensor-value" id="heart_rate_value">--</div>
                  <div class="sensor-unit">bpm</div>
                  <div class="sensor-label">SPO2 Levels</div>
                  <div class="sensor-value" id="spo2_value">--</div>
                  <div class="sensor-unit">%</div>
                  <div class="sensor-label">Temperature</div>
                  <div class="sensor-value" id="temp_value">--</div>
                  <div class="sensor-unit">°C</div>
                  <div class="sensor-label">Accelerometer Data</div>

                  <div class="alert-message" id="accelerometer_message">--</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script>
      $(document).ready(function () {
        var dps1 = [];
        var dps2 = [];
        var dps3 = [];
        let dps4 = [];

        var updateInterval = 200;

        var chart1 = new CanvasJS.Chart("chartContainer1", {
          title: { text: "ECG" },
          data: [{ type: "line", dataPoints: dps1 }],
        });

        var chart2 = new CanvasJS.Chart("chartContainer2", {
          title: { text: "Heart Rate" },
          data: [{ type: "line", dataPoints: dps2 }],
          axisY: {
            includeZero: true,
            suffix: "bpm",
          },
        });

        var chart3 = new CanvasJS.Chart("chartContainer3", {
          title: { text: "SPO2 Levels" },
          data: [{ type: "line", dataPoints: dps3 }],
          axisY: {
            includeZero: true,
            suffix: "%",
          },
        });

        let chart4 = new CanvasJS.Chart("chartContainer4", {
          title: { text: "Temperature" },
          axisY: {
            title: "Temperature",
            titleFontColor: "#4F81BC",
            includeZero: true,
            suffix: "°C",
            crosshair: {
              enabled: true,
              snapToDataPoint: true,
            },
          },
          axisX: {
            crosshair: {
              enabled: true,
              snapToDataPoint: true,
            },
          },

          data: [{ type: "area", dataPoints: dps4 }],
        });

        function updateChart(chart, dataPoints, newDataPoint) {
          dataPoints.push(newDataPoint);
          if (dataPoints.length > 300) {
            dataPoints.shift();
          }
          chart.render();
        }

        function fetchSensorData() {
          $.ajax({
            type: "GET",
            url: "{% url 'MonitoringApp:fetch_sensor_values_ajax' %}",
            success: function (data) {
              if (data.result) {
                var sensorData = data.result;
                var timestamp = new Date(sensorData.timestamp);

                updateChart(chart1, dps1, {
                  x: timestamp,
                  y: sensorData.ecg_data,
                });
                updateChart(chart2, dps2, {
                  x: timestamp,
                  y: sensorData.heart_rate,
                });
                updateChart(chart3, dps3, {
                  x: timestamp,
                  y: sensorData.spo2_level,
                });
                updateChart(chart4, dps4, {
                  x: timestamp,
                  y: sensorData.temp,
                });

                // Display sensor data
                $("#ecg_value").text(sensorData.ecg_data);
                $("#heart_rate_value").text(sensorData.heart_rate);
                $("#spo2_value").text(sensorData.spo2_level);
                $("#temp_value").text(sensorData.temp);

                // Display fall detection message
                if (data.fall_detected) {
                  $("#accelerometer_message")
                    .text("Fall detected")
                    .addClass("fall-detected")
                    .removeClass("nofall");
                  alert("Fall detected!!!");
                } else {
                  $("#accelerometer_message")
                    .text("No fall detected")
                    .addClass("nofall")
                    .removeClass("fall-detected");
                }
                console.log(data.heart_rate);
                // CAZURI RITM CARDIAC
                // if (data.heart_rate < 40) {
                //   alert(
                //     "Ritmul cardiac: " +
                //       data.heart_rate +
                //       " bpm - scăzut (Bradicardie)!!"
                //   );
                // } else if (data.heart_rate >= 40 && data.heart_rate < 60) {
                //   alert(
                //     "Ritm cardiac scăzut: " +
                //       data.heart_rate +
                //       " bpm - Alertă pentru bradicardie moderată!!"
                //   );
                // } else if (data.heart_rate >= 60 && data.heart_rate <= 100) {
                //   // Interval normal al ritmului cardiac
                // } else if (data.heart_rate > 100 && data.heart_rate <= 140) {
                //   alert(
                //     "Ritmul cardiac ridicat: " +
                //       data.heart_rate +
                //       " bpm - Alertă pentru tahicardie."
                //   );
                // } else if (data.heart_rate > 140) {
                //   alert(
                //     "Ritmul cardiac foarte ridicat! Alertă pentru tahicardie severă. Ritm cardiac: " +
                //       data.heart_rate +
                //       " bpm"
                //   );
                // }
              } else {
                console.log("Error: Fara date de la senzori primite.");
              }
            },
            error: function () {
              console.log("Error: Failed to fetch sensor data.");
            },
          });
        }

        setInterval(fetchSensorData, updateInterval);
      });
    </script>
  </body>
{% endblock %}

IoTPlatform/MonitoringApp/templates/MonitoringApp/login.html
{% extends 'MonitoringApp/base.html'%} {% load static %} {% block body %}
<link
  rel="stylesheet"
  type="text/css"
  href="{%static 'login-style/login.css'%}"
/>

<div class="father">
  <div class="container login-container">
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input
          class="form-control"
          placeholder="Enter Username"
          name="username"
        />
        <!-- <small id="emailHelp" class="form-text text-muted"
          >We'll never share your email with anyone else.</small
        > -->
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input
          type="password"
          class="form-control"
          id="exampleInputPassword1"
          placeholder="Password"
          name="password"
        />
      </div>

      <button type="submit" class="btn btn-primary mt-3">Submit</button>
      <p class="reg-link py-3">
        <a href="{% url 'MonitoringApp:register_view' %}"
          >You don't have an account?</a
        >
      </p>
    </form>
  </div>
  <img class="img-medici" src="{% static 'mainPage/medici.png'%}" alt="" />
</div>

{% endblock %}

IoTPlatform/MonitoringApp/templates/MonitoringApp/register.html
{% extends "MonitoringApp/base.html" %} {% block body %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{%static 'register/register.css'%}"
/>
<h1>Register</h1>
<form method="post">
  {% csrf_token %}
  <div class="myform form-row">
    <div class="col-3">
      <label for="">First name</label>
      <input type="text" class="form-control" placeholder="First name" />
    </div>
    <div class="col-3 pt-3">
      <label for="">Last name</label>
      <input type="text" class="form-control" placeholder="Last name" />
    </div>
    <div class="col-3 pt-3">
      <label for="exampleInputEmail1">Email address</label>
      <input
        type="email"
        class="form-control"
        id="exampleInputEmail1"
        aria-describedby="emailHelp"
        placeholder="Enter email"
      />
      <small id="emailHelp" class="form-text text-muted"
        >We'll never share your email with anyone else.</small
      >
    </div>
    <div class="col-3 pt-3">
      <label for="">Username</label>
      <input
        type="text"
        class="form-control"
        placeholder="Username"
        name="username"
      />
    </div>

    <div class="col-3 pt-3">
      <label for="inputPassword2" class="sr-only">Password</label>
      <input
        type="password"
        class="form-control"
        id="inputPassword2"
        placeholder="Password"
        name="password"
      />
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
  </div>
</form>

{% endblock body %}